### ISSUE TITLE
Change the versioning scheme of gorilla

### ISSUE THREAD

**Issue by erikng** [1dustindavis/gorilla#101]
Gorilla has had 13 commits since beta 4, but there isn't a beta 5 yet. This makes it problematic to maintain internally if say we want to deploy our own version in the mean time and then you release beta 5.

Could we move towards something like 1.0.0.4 (with a prerelease version)?. Then we could internally do something like 1.0.0.4.1 up to 1.0.0.4.999999 until you release new version.

**Comment by 1dustindavis** [comment]
This was implemented in version 1.0.0.5
