### ISSUE TITLE
mTLS gives error:  x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sfc-gh-pjoshi** [1dustindavis/gorilla#118]
Sample config File:
url: https://YourWebServer/gorilla/
manifest: example
catalogs: 
  - alpha
  - beta
app_data_path: C:/gorilla/cache
auth_user: GorillaRepoUser
auth_pass: pizzaisyummy
tls_auth: true
tls_client_cert: c:/certs/client.pem
tls_client_key: c:/certs/client.key
tls_server_cert: c:/certs/server.pem

Have created the client and server certs and provided their absolute paths in the config file's TLS settings. Still getting the error : x509: certificate signed by unknown authority

**Comment by 1dustindavis** [comment]
Hi @sfc-gh-pjoshi, its hard to say what the issue is without more details. It could definitely be an issue with Gorilla, but it also could be an issue with the certificate of mTLS server.

It might be helpful to check the server logs to see if the correct certificate is being presented.
