### ISSUE TITLE
Feature Request: default manifest and url if not specified in config.yaml

### ISSUE THREAD

**Issue by serrc-techops** [1dustindavis/gorilla#122]
Having default manifests and urls built into the gorilla binary similar to munki would be handy for getting un-configured clients communicating with the server and integrated. This would allow the use of a generic gorilla installer on a client device and then the proper configuration could be provided by the server.

**Comment by grahamgilbert** [comment]
A default manifest is fine, but I would argue that a default URL is a security risk. All I need to do is put a server up at http://gorilla and set a search domain and you've got a compromised device.

**Comment by serrc-techops** [comment]
Very true about the security risk. I was thinking the default url would more be used temporarily by a client, with the proper configuration being set by whatever method from the gorilla server when first connected. Maybe that too is not secure enough.

**Comment by 1dustindavis** [comment]
@serrc-techops I think this is a pretty commonly used feature of Munki, but I agree with Graham that any implementation of a default URL is a huge security risk. Anything in the Gorilla repo has the ability to run as an admin on all your devices.

If you wanted Gorilla to self-configure, I could see us adding support for something like `gorilla.exe -url https://gorilla.domain.xyz`. If you had an item in Gorilla that deployed a config.yaml, that would sort of bootstrap it, but someone would need to provide the url somehow (either in the config or at the command line).

It would probably be easier and more dependable to just put the config.yaml on disk when you put gorilla.exe there. (Don't forget, you also need a way for gorilla to run on a schedule. We use task scheduler.)

We use [Chef to deploy Gorilla](https://github.com/uber/client-platform-engineering/tree/main/chef/cookbooks/cpe_gorilla) and it's configuration, and I would highly recommend a Configuration Management tool to be used along side Gorilla, but I understand that could be a lot to take on.

It would also be possible to build a custom MSI (or go binary!) that deploys gorilla.exe and config.yaml.
