### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by MalteKiefer** [1dustindavis/gorilla#126]
Is this project still alive?

**Comment by 1dustindavis** [comment]
It's alive in the sense that Gorilla is still used by various companies, including my employer. I don't have time to contribute to the repo, but very open to PRs.

**Comment by 1dustindavis** [comment]
The last release was three years ago, but we have not had any need for bug fixes or improvements that affect our usage, so there is nothing motivating a release.

The project was also created with minimal external dependencies, but it would probably be worth issuing a new release with the latest go runtime. 

If I had significantly more free time, the number one feature would work on would be some sort of user interface that would allow users to optionally select software to install.

**Comment by MalteKiefer** [comment]
Thank you for the quick response.
I think I would be very happy to help, unfortunately my knowledge of golang is really minimal.

A self store GUI like this would be really nice, where users could choose what to install with a click.
Actually, this would also be possible with a simple web-front.
In the sense of binding a catalog to a user with SSO (e.g. Azure AD). The user logs in, selects the software, a new manifest is created, and the agent does the rest.

This way, the agent remains minimal and does not have to be extended by a GUI, max by a user link.

Or a device ID bound to the manifest.

**Comment by 1dustindavis** [comment]
I have not considered solving the problem server side, but that would definitely work and would require zero changes to gorilla on the client. 

For our use case, I think we would still prefer a local UI.

**Comment by MalteKiefer** [comment]
Ok, that would be nice too.
Would you make it in the style of munki?

**Comment by 1dustindavis** [comment]
I assume we would attempt to mimic the UI style of the Microsoft Store.

**Comment by MalteKiefer** [comment]
So there should be a switch in the config that says store:(true|false) where there is a gui afterwards.

Then the store must load the catalog and the automatic installations are continued in the manifest.

A manifest would then also have to be created locally that includes the base manifest and also lists the apps that were installed via the store, with automatic updating.

**Comment by 1dustindavis** [comment]
The interaction between the UI and the current CLI tool is probably the hardest part of getting a working UI. It may require significant changes to the CLI to support some method of cross process communication.

**Comment by MalteKiefer** [comment]
That's the reason why I said that the web GUI is the better solution.

**Comment by MalteKiefer** [comment]
Maybe a good GUI framework: https://github.com/fyne-io/

**Comment by 1dustindavis** [comment]
Yeah, there is not a shortage of UI frameworks. PRs welcomed 😅

**Comment by 1dustindavis** [comment]
Closing this issue for now, but always happy to chat!
