### ISSUE TITLE
Feature Request: Implement Gorilla as Service

### ISSUE THREAD

**Issue by gyamada619** [1dustindavis/gorilla#33]
It would be great to see the compiled Gorilla binary install as a service by default, and run every 30 minutes, just like the chef client. It seems likely to me that something like the below repo could make doing this relatively straightforward. I may attempt to do this myself at some point unless someone beats me to it. 

[go-windows-svc](https://github.com/billgraziano/go-windows-svc)

**Comment by 1dustindavis** [comment]
This seems like a good deployment option, but I don't think that should be the default behavior of the exe. It might make sense to offer an MSI that configures a service or scheduled task.

**Comment by gyamada619** [comment]
You're probably right. An MSI would be great!
