### ISSUE TITLE
installer_item_hash should not be case sensitive

### ISSUE THREAD

**Issue by gyamada619** [1dustindavis/gorilla#35]
I've got a test instance of Gorilla set up now, and I've got an example manifest that's supposed to download FileZilla. But when I run Gorilla on the endpoint, it finds the manifest and catalog it's supposed to, and hits this error. When I compare the hashes using Get-FileHash, they prove to be identical. Any idea what might be causing this?

[gorilla.log](https://github.com/1dustindavis/gorilla/files/2597795/gorilla.log)

**Comment by gyamada619** [comment]
Looks like I solved my own issue. Hash has to be lowercase. Whoops!

**Comment by 1dustindavis** [comment]
Does `Get-FileHash` output an uppercase hash? I guess gorilla should probably accept it either way? 🤔

**Comment by 1dustindavis** [comment]
We should convert the admin provided sha to lowercase before comparing.
https://github.com/1dustindavis/gorilla/blob/7459c2434ad1bd9189db63d4545e4e5e1776a48c/pkg/download/download.go#L140
should become something like `if shaHash != strings.ToLower(sha) {`

**Comment by 1dustindavis** [comment]
@gyamada619 Appreciate the help! Here is a release that should solve your issue: https://github.com/1dustindavis/gorilla/releases/tag/v1.0.0-alpha.8

**Comment by gyamada619** [comment]
Thanks! This saves me from adding a transform to my import script.
