### ISSUE TITLE
Fails when Uninstall String does not exist

### ISSUE THREAD

**Issue by YourCrush** [1dustindavis/gorilla#37]
https://github.com/1dustindavis/gorilla/blob/d5737f089a85ee8948da2b757af684e46dfcbb5e/pkg/status/status.go#L82

If uninstall string is not a value in any single key in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\` Gorilla panics with error `Unable to read UninstallStringThe system cannot find the file specified.`

For example, I have the SCCM client installed (Configuration Manager Client), and it does not have an uninstall string. Everything else in the above registry path does. From what I can tell of the code, it is trying to check if everything in that path has an uninstall string. Since this does not, it panics.

@gyamada619 and I found this while testing.

**Comment by YourCrush** [comment]
Got around this by adding an `install_check_path` to the catalog item. But it's still just a workaround.

**Comment by 1dustindavis** [comment]
Yeah, all of `uninstall` probably needs to be reviewed and considered. The registry thing is pretty silly and unreliable.

**Comment by 1dustindavis** [comment]
Yeah, that would keep it from causing a panic, but the uninstall process still needs to be rethought.
