### ISSUE TITLE
Uninstall Function Downloads Installer Again?

### ISSUE THREAD

**Issue by gyamada619** [1dustindavis/gorilla#40]
https://github.com/1dustindavis/gorilla/blob/37d149e52e0f634a84d87b01f2daf0ffe578f84d/pkg/installer/installer.go#L175

It looks like the `uninstall` function in `installer.go` runs the same code in the `install` function and downloads the installer file again right before it runs the uninstaller. I'm not sure if this was intentional? If it's not needed, let's remove it.

**Comment by 1dustindavis** [comment]
You are right that this is silly, but it is mostly because Choco and MSI use the original package to uninstall so we have to re-download it if we don't already have it.

This will all be replaced/rethought with this issue: #28
