### ISSUE TITLE
Strict type handling

### ISSUE THREAD

**Issue by erikng** [1dustindavis/gorilla#57]
Gorilla should probably do strict type handling on the various data types passed to the yaml catalogs.

If you pass a wrong type of value (say for instance a string vs an array) to one of the keys, gorilla will currently blow up when processing the catalog files.

Rather than completely blow up, it should be able to log and help the admin debug the issue.

**Comment by 1dustindavis** [comment]
The types are already strict, we probably just need better error reporting when unmarshalling yaml.
