### ISSUE TITLE
PowerShell file hash differs when it is multi-line.

### ISSUE THREAD

**Issue by YourCrush** [1dustindavis/gorilla#62]
Created a package that was a PowerShell script, multi-line. When Gorilla downloaded the file, the hash was different than when I added it to the catalog, so it threw an error and exited. 

Pretty sure it is because of Windows end-line characters. When I re-created the script and put all the lines on one line separated by a semicolon it worked flawlessly. It may have something to do with how Gorilla gets this script from the web server (straight up downloading it, or "re-creating" the file in real-time). Either way, this seems problematic for larger PowerShell scripts.

**Comment by erikng** [comment]
You should make sure that when you save the files, your IDE isn't adding extra stuff. Can't say I've seen this error and we have several large powershell scripts. 

It could be some kind of carrier return or encoding issue. 

We use git with an automation pipeline - are you manually uploading these files yourself?

**Comment by 1dustindavis** [comment]
A hash should not be affected by line-endings. 

How are you hosting the files? If you manually download the files from the server and check the hash, what do you get?

**Comment by YourCrush** [comment]
The file was created on VS Code on a Windows machine, using Windows line endings. We re-typed the script (multi-lined), uploaded it, and manually kicked off a Gorilla run on the endpoint, and it still returned a different hash on the endpoint than what was originally created and being uploaded onto the webserver. 

I'll look more into what was going on; one of my colleagues seems to think it has something to do with the process of getting the files onto the webserver (committing to a git repo, then being pulled over via Chef).

**Comment by gyamada619** [comment]
We now suspect that the culprit is `haproxy` changing the file to `LF` end-of-line upon a request for the file from the web server. We're going to attempt re-creating the file with `LF` end-of-line sequences, re-uploading to the server, and then trying a gorilla run again.

Apparently EOL sequences do change the hash. /shrug

**Comment by erikng** [comment]
It's because it's a different encoding.

**Comment by 1dustindavis** [comment]
Glad you found a potential cause!

Ideally your web server would serve content exactly as it is, without any modifications. But understanding what is really going on allows you to work around it.

Any change to the file (content, line endings, or encoding, etc) would change the hash.

Let us know the outcome of testing the line ending changes.

**Comment by 1dustindavis** [comment]
@YourCrush @gyamada619 Any luck getting confirmation this was caused by haproxy?

**Comment by gyamada619** [comment]
As far as we can tell, yup, that was it. Sorry for not getting back over here sooner to confirm! Appreciate you checking in and verifying.
