### ISSUE TITLE
Middleware or Built-In Integration With Cloud Repo

### ISSUE THREAD

**Issue by gyamada619** [1dustindavis/gorilla#63]
I cobbled together some code for a section of the `download` package that can connect to a Backblaze B2 bucket and grab code & packages from a gorilla repo inside said bucket. Feel free to integrate or use at your discretion @1dustindavis; I have no plans to implement it in our environment anymore since we decided to go with an on-prem server.

Code is [in a Gist over here](https://gist.github.com/gyamada619/4d445cf1cf71102d72eaa617e8127c52).

**Comment by 1dustindavis** [comment]
Thanks Garrett! I am going to close this issue as a duplicate of #30, but the gist could be super helpful for understanding how to best add support generic middleware!
