### ISSUE TITLE
Gorilla Process Hangs When Running .ps1

### ISSUE THREAD

**Issue by gyamada619** [1dustindavis/gorilla#80]
@1dustindavis here's a GitHub issue, as promised:

Gorilla is running some `.ps1` scripts for us, a few of which install some Chocolatey packages as part of the script to ensure some things are present for the rest of the script to run successfully (these are packages on our internal Chocolatey repo, and we update them frequently via an existing build pipeline, making it inconvenient, but not impossible, to update the raw `.nupkg` files on the gorilla server). 

With beta 2, these scripts run exactly as we expect. With beta 3, however, these scripts hang on the Chocolatey package step of the script (`choco install example`). Gorilla never terminates.

Perhaps importantly (or not), Gorilla is being run as a scheduled task as an Active Directory service account user. I don't think this is part of the issue, as the run succeeds on beta 2, but  the more info the better for troubleshooting.

**Comment by YourCrush** [comment]
To add on to this:

Gorilla will successfully spawn off a chocolatey process, but hangs shortly after. If we kill the gorilla process, the chocolatey process un-hangs and continues on with no issues.

**Comment by 1dustindavis** [comment]
Beta 3 included changes to the way stdout and stderr are processed in [this commit](https://github.com/1dustindavis/gorilla/commit/87acbb84fc3938a5da95cdec3f04800062acdffe).

My suspicion after a quick glance is that this is related to the `WaitGroup` that was [added here](https://github.com/1dustindavis/gorilla/commit/87acbb84fc3938a5da95cdec3f04800062acdffe#diff-4b35ff35fbd91ac2061f732a0a7c801dR44).
