### ISSUE TITLE
Status Checks enhancement: Add registry check under HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\

### ISSUE THREAD

**Issue by mbadan2** [1dustindavis/gorilla#85]
Would be great if Gorilla can detect apps under Wow6432Node registry entry. We're working around this by using the file and script check for now.

**Comment by cakiwi** [comment]
@mbadan2  Thanks for this. One of my apps has no File Version. And no --version flag . This location did have the version though.  I could PS script it.

**Comment by 1dustindavis** [comment]
This should be resolved with #89
